### ISSUE TITLE
Not working on Termux

### ISSUE THREAD

**Issue by TheShubhendra** [pytgcalls/pytgcalls#121]
```python
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 403, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 302, in <module>
    set_scputimes_ntuple("/proc")
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 405, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 269, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/stat'
Traceback (most recent call last):
  File "/storage/emulated/0/shubhendra/bot/telegram/ban-channel-accounts-in-vc/test.py", line 11, in <module>
    from pytgcalls import PyTgCalls
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pytgcalls/__init__.py", line 2, in <module>
    from .methods.custom_api.custom_api import CustomAPI
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pytgcalls/methods/__init__.py", line 3, in <module>
    from .core import Core
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pytgcalls/methods/core/__init__.py", line 10, in <module>
    from .spawn_process import SpawnProcess
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pytgcalls/methods/core/spawn_process.py", line 2, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/data/data/com.termux/files/usr/lib/python3.10/collections/__init__.py)
```

**Comment by Laky-64** [comment]
What version of pytgcalls are you using?

**Comment by TheShubhendra** [comment]
> What version of pytgcalls are you using?

 Latest one - v0.8.0

**Comment by tappo03** [comment]
You're using the wrong version use: pip3 install py-tgcalls==0.8.1rc1 -U for install the latest version

**Comment by TheShubhendra** [comment]
> You're using the wrong version use: pip3 install py-tgcalls==0.8.1rc1 -U for install the latest version

```python
u0_a665@localhost /s/s/b/d/quora-discord (main)> pip3 install py-tgcalls==0.8.1rc1 -U
ERROR: Could not find a version that satisfies the requirement py-tgcalls==0.8.1rc1 (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0)
ERROR: No matching distribution found for py-tgcalls==0.8.1rc1
```

**Comment by tappo03** [comment]
It's your issue with pypi, the oldest stable version is 0.8.0 (https://pypi.org/project/py-tgcalls)

**Comment by tappo03** [comment]
> Actually I have `python-3.10.0` installed that is not listed in classifier in setup.py. Is the library not supported by `python-3.10.0` ?

I have already sent you the version which supports python 3.10
