### ISSUE TITLE
Group Call Not Found

### ISSUE THREAD

**Issue by L1ch-K1ng** [pytgcalls/pytgcalls#160]
**Describe the bug**
When the bot runs, he can't find any group calls. The chat_call variable in line 222 (https://github.com/pytgcalls/pytgcalls/blob/master/pytgcalls/methods/groups/join_group_call.py) is empty even when a group call is currently running.

**To Reproduce**
1. Create a py file with "simple_calls" example code
2. Set your pyrogram values (bot_token, api_id, api_hash)
3. run the script

**Expected behavior**
The bot should join into the open voice chat an play the example audio file

**Log**
```
Group call not found with the chat id XXX (I removed the group chat id)
Traceback (most recent call last):
  File "C:\%OBFUSCATED%\venv\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\%OBFUSCATED%\test.py", line 28, in play_handler
    print(call_py.get_active_call(message.chat.id))
  File "C:\%OBFUSCATED%\venv\lib\site-packages\pytgcalls\methods\groups\get_active_call.py", line 45, in get_active_call
    return self._call_holder.get_active_call(
  File "C:\%OBFUSCATED%\venv\lib\site-packages\pytgcalls\types\call_holder.py", line 43, in get_active_call
    raise GroupCallNotFound(chat_id)
pytgcalls.exceptions.GroupCallNotFound: Group call not found with the chat id XXX (I removed the group chat id)
```

**Version Information:**
 - OS: Win 10 (up-to-date)
 - pytgcalls v0.9.1
 - Pyrogram v2.0.35
 - NodeJS v18.7.0
 - Python v3.10

**Comment by Laky-64** [comment]
You can't join with bots, only with userbots
