### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KSKOP69** [pytgcalls/pytgcalls#190]
**Log**
```
[25-Nov-23 18:34:51 - ERROR] - pyrogram.dispatcher - 'ChannelForbidden' object has no attribute 'chat_id'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/opt/venv/lib/python3.11/site-packages/pytgcalls/mtproto/pyrogram_client.py", line 98, in on_update
    chat_id = self.chat_id(data2[update.chat_id])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pytgcalls/mtproto/bridged_client.py", line 98, in chat_id
    return -input_peer.chat_id
            ^^^^^^^^^^^^^^^^^^
AttributeError: 'ChannelForbidden' object has no attribute 'chat_id'
```

**Linux (please complete the following information):**
 - OS: [Linux]
 - Python Version [3.11.4]

**Comment by AnonymousX1025** [comment]
Skill issues

**Comment by KSKPAPA** [comment]
> Skill issues

Are you saying who made pytgcalls.
Dont have skills.

**Comment by KSKPAPA** [comment]
Btw i haven't made yukki repo And i dont have skills.
If You know tell the issue instead of talking bullshit.
And tease and making fun of others.
If cant help then keep quite.

**Comment by Laky-64** [comment]
This isn't a pytgcalls related issue
