### ISSUE TITLE
ImportError: cannot import name 'EditGroupCallParticipant' from 'pyrogram.raw.functions.phone' 

### ISSUE THREAD

**Issue by SuperCosmicBeing** [pytgcalls/pytgcalls#20]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from callsmusic import run
  File "/app/callsmusic/__init__.py", line 1, in <module>
    from .callsmusic import pytgcalls, run
  File "/app/callsmusic/callsmusic.py", line 2, in <module>
    from pytgcalls import PyTgCalls
  File "/usr/local/lib/python3.7/dist-packages/pytgcalls/__init__.py", line 2, in <module>
    from .methods.logs.py_logs import PyLogs  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytgcalls/methods/__init__.py", line 8, in <module>
    from .websocket import WebSocket
  File "/usr/local/lib/python3.7/dist-packages/pytgcalls/methods/websocket/__init__.py", line 2, in <module>
    from .change_volume_voice_call import ChangeVolumeVoiceCall
  File "/usr/local/lib/python3.7/dist-packages/pytgcalls/methods/websocket/change_volume_voice_call.py", line 5, in <module>
    from pyrogram.raw.functions.phone import EditGroupCallParticipant
ImportError: cannot import name 'EditGroupCallParticipant' from 'pyrogram.raw.functions.phone' (/usr/local/lib/python3.7/dist-packages/pyrogram/raw/functions/phone/__init__.py)

**Comment by Laky-64** [comment]
Fix by follow this lines

pip3 uninstall pyrogram
pip3 install git+https://github.com/pyrogram/pyrogram -U

**Comment by BlackStoneReborn** [comment]
> Fix by follow this lines
> 
> ```shell
> pip3 uninstall pyrogram
> pip3 install git+https://github.com/pyrogram/pyrogram -U
> ```

I guess you can close this now, @Laky-64

**Comment by rojserbest** [comment]
@Laky-64 you don't need to uninstall if you use `-U`.

**Comment by Laky-64** [comment]
Ok, now i close this issue because is solved
