### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by Mohammadwh** [pytgcalls/pytgcalls#216]
**Linux (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic aarch64)
 - Python Version 3.10

i want to install py-tgcalls but get this error:

Building wheels for collected packages: ntgcalls
  Building wheel for ntgcalls (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [84 lines of output]
      running bdist_wheel
      running build
      running build_ext
      CMake Installer Version: 3.28.1, Copyright (c) Kitware
      This is a self-extracting archive.
      The archive will be extracted to: /tmp/pip-install-0n9w1xko/ntgcalls_13b4bbabde4c4f12a723f6dd36ac9fe5/build_tools/cmake_3_28_1

      Using target directory: /tmp/pip-install-0n9w1xko/ntgcalls_13b4bbabde4c4f12a723f6dd36ac9fe5/build_tools/cmake_3_28_1
      Extracting, please wait...

      Unpacking finished successfully
      -- The C compiler identification is unknown
      -- The CXX compiler identification is unknown
      CMake Error at CMakeLists.txt:18 (project):
        The CMAKE_C_COMPILER:

          clang-18

        is not a full path and was not found in the PATH.

        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.

      CMake Error at CMakeLists.txt:18 (project):
        The CMAKE_CXX_COMPILER:

          clang++-18

        is not a full path and was not found in the PATH.

        Tell CMake where to find the compiler by setting either the environment
        variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
        to the compiler, or to the compiler name if it is in the PATH.

      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-0n9w1xko/ntgcalls_13b4bbabde4c4f12a723f6dd36ac9fe5/setup.py", line 283, in <module>
          setup(
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 89, in run
          _build_ext.run(self)
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-install-0n9w1xko/ntgcalls_13b4bbabde4c4f12a723f6dd36ac9fe5/setup.py", line 208, in build_extension
          subprocess.run(
        File "/usr/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '[PosixPath('/tmp/pip-install-0n9w1xko/ntgcalls_13b4bbabde4c4f12a723f6dd36ac9fe5/build_tools/cmake_3_28_1/bin/cmake'), '/tmp/pip-install-0n9w1xko/ntgcalls_13b4bbabde4c4f12a723f6dd36ac9fe5', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-0n9w1xko/ntgcalls_13b4bbabde4c4f12a723f6dd36ac9fe5/build/lib.linux-aarch64-cpython-310/', '-DPYTHON_EXECUTABLE=/www/selfbot/911eb1275d71c15c1a562653ed0fb694_venv/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION_INFO=1.1.0', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=/tmp/pip-install-0n9w1xko/ntgcalls_13b4bbabde4c4f12a723f6dd36ac9fe5/build/lib.linux-aarch64-cpython-310', '-DCMAKE_CXX_FLAGS=-D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE', '-DCMAKE_C_COMPILER=clang-18', '-DCMAKE_CXX_COMPILER=clang++-18', '-DCMAKE_CXX_FLAGS=-D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ntgcalls
  Running setup.py clean for ntgcalls
Failed to build ntgcalls
ERROR: Could not build wheels for ntgcalls, which is required to install pyproject.toml-based projects

please help me

**Comment by Laky-64** [comment]
If you are on arm64, follow this build guide:
https://pytgcalls.github.io/NTgCalls/Build%20Guide

**Comment by Mohammadwh** [comment]
thanks ❤
