### ISSUE TITLE
packages/pytgcalls/group_call_native.py", line 449, in GroupCallNative                        def __set_connection_mode(self, mode: tgcalls.GroupConnectionMode, keep_broadcast_if_was_enabled=False): AttributeError: partially initialized module 'tgcalls' has no attribute 'GroupConnectionMode' (most likely due to a circular import)

### ISSUE THREAD

**Issue by FarhanArt** [pytgcalls/pytgcalls#24]
```
Proceed (y/n)? y                                                  Successfully uninstalled Pyrogram-1.1.13                      root@localhost:~/DonateRemosa# pip3 install git+https://github.com/pyrogram/pyrogram -U                                         Collecting git+https://github.com/pyrogram/pyrogram               Cloning https://github.com/pyrogram/pyrogram to /tmp/pip-req-build-vqr89dlh                                                     Running command git clone -q https://github.com/pyrogram/pyrogram /tmp/pip-req-build-vqr89dlh                                 Requirement already satisfied: async_lru==1.0.2 in /usr/local/lib/python3.9/dist-packages (from Pyrogram==1.1.13) (1.0.2)       Requirement already satisfied: pyaes==1.6.1 in /usr/local/lib/python3.9/dist-packages (from Pyrogram==1.1.13) (1.6.1)           Requirement already satisfied: pysocks==1.7.1 in /usr/local/lib/python3.9/dist-packages (from Pyrogram==1.1.13) (1.7.1)         Building wheels for collected packages: Pyrogram                  Building wheel for Pyrogram (setup.py) ... done                 Created wheel for Pyrogram: filename=Pyrogram-1.1.13-py3-none-any.whl size=2837704 sha256=4b7cdbd7eb3a950bdcabb5f571327dd4b4bed59327b7f55438426e9bcc944aca                                      Stored in directory: /tmp/pip-ephem-wheel-cache-dfwwzdod/wheels/16/c3/66/f89f9a6b4b40d4d6189b1dca81cfaffb0b51ffe0866ba6806d   Successfully built Pyrogram                                     Installing collected packages: Pyrogram                         Successfully installed Pyrogram-1.1.13                          root@localhost:~/DonateRemosa# python3 main.py                  Traceback (most recent call last):                                File "/root/DonateRemosa/main.py", line 3, in <module>            from tgcalls import run                                       File "/root/DonateRemosa/tgcalls/__init__.py", line 1, in <module>                                                                from .tgcalls import pytgcalls, run                           File "/root/DonateRemosa/tgcalls/tgcalls.py", line 2, in <module>                                                                 from pytgcalls.pytgcalls import PyTgCalls
  File "/usr/local/lib/python3.9/dist-packages/pytgcalls/__init__.py", line 20, in <module>
    from pytgcalls.group_call_native import GroupCallNative, GroupCallNativeAction, GroupCallNativeDispatcherMixin                File "/usr/local/lib/python3.9/dist-packages/pytgcalls/group_call_native.py", line 71, in <module>                                class GroupCallNative(GroupCallNativeDispatcherMixin):
  File "/usr/local/lib/python3.9/dist-packages/pytgcalls/group_call_native.py", line 449, in GroupCallNative                        def __set_connection_mode(self, mode: tgcalls.GroupConnectionMode, keep_broadcast_if_was_enabled=False):
AttributeError: partially initialized module 'tgcalls' has no attribute 'GroupConnectionMode' (most likely due to a circular import)
```

I've tried reinstalling pyrogram but still have the same problem
Please fix this :(

**Comment by Laky-64** [comment]
Run just

``` bash
pip uninstall pytgcalls
pip install py-tgcalls
```

**Comment by FarhanArt** [comment]
I will try it but don't close the issue 
before the problem is resolved :)

**Comment by Laky-64** [comment]
Have you solved your problem?

**Comment by KangPaste** [comment]
Yes i try and problem solved 
Thank :D
