### ISSUE TITLE
The mp3 files can't play with newer version of py-tgcalls

### ISSUE THREAD

**Issue by mtalaeii** [pytgcalls/pytgcalls#254]
**Describe the bug**
The mp3 files can't play with newer version of py-tgcalls. In this version i cant play mp3 files (using local path)

## Edited :
So its seems to be more than that and its cant even stream video files too
So i'm going to share entire log :)

**To Reproduce**
I used [This example](https://github.com/pytgcalls/pytgcalls/blob/master/example/piped_audio_calls/example_piped_audio.py) and pass download path to it as you know its mp3 but its cant be played!

**Expected behavior**
Play the audio file

**Log**

Traceback (most recent call last):
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/hydrogram/dispatcher.py", line 236, in _handle_update
    await self._execute_callback(handler, parsed_update)
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/hydrogram/dispatcher.py", line 264, in _execute_callback
    await handler.callback(self.client, *args)
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/hydrogram/handlers/message_handler.py", line 170, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/Mahdi/StreamBot/helpers/decorators.py", line 30, in wrapper
    await func(client,message)
  File "/home/Mahdi/StreamBot/plugins/video_stream.py", line 15, in audio_stream
    await calls.play(
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/pytgcalls/mutex.py", line 9, in async_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/pytgcalls/statictypes.py", line 96, in async_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/pytgcalls/mtproto_required.py", line 23, in async_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/pytgcalls/methods/stream/play.py", line 87, in play
    result_params = await self._app.join_group_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/pytgcalls/mtproto/mtproto_client.py", line 62, in join_group_call
    return await self._bind_client.join_group_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/pytgcalls/mtproto/hydrogram_client.py", line 386, in join_group_call
    result: Updates = await self._app.invoke(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/hydrogram/methods/advanced/invoke.py", line 85, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/hydrogram/session/session.py", line 424, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/hydrogram/session/session.py", line 344, in send
    message = self.msg_factory(data)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/hydrogram/session/internals/msg_factory.py", line 39, in __call__
    len(body),
    ^^^^^^^^^
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/hydrogram/raw/core/tl_object.py", line 78, in __len__
    return len(self.write())
               ^^^^^^^^^^^^
  File "/home/Mahdi/StreamBot/.venv/lib/python3.12/site-packages/hydrogram/raw/functions/phone/join_group_call.py", line 105, in write
    b.write(self.join_as.write())
            ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write'

**Linux (please complete the following information):**
 - OS: Arch Linux x86_64 - 6.10.10-arch1-1
 - Python Version : 3.12.6

**Comment by Laky-64** [comment]
That doesn't sound pytgcalls related, but more pyrogram related

**Comment by mtalaeii** [comment]
> That doesn't sound pytgcalls related, but more pyrogram related

No it's pytgcalls bug because i cant find flag that we forced that audio's media just used voice to be streamed and its always stream as video!!

**Comment by mtalaeii** [comment]
Fixed the mistake is from myside
