### ISSUE TITLE
Pyrogram Cast problem

### ISSUE THREAD

**Issue by amirwolf5122** [pytgcalls/pytgcalls#267]
Why does the call not work? It enters the call, but when it wants to play, it gives an error and exits
```

from telethon import TelegramClient, events,sessions,functions, types,errors,extensions,Button
from pytgcalls import PyTgCalls
from pytgcalls import idle
from pytgcalls.types import MediaStream
import logging
logging.basicConfig(filename='die.txt',
                    filemode='a',
                    format='%(asctime)s,%(msecs)d %(name)s %(levelname)s %(message)s',
                    datefmt='%H:%M:%S',
                    level=logging.DEBUG)
logger = logging.getLogger(__name__)
idapi=123
hashapi='123'

app = TelegramClient("hi", api_id=idapi, api_hash=hashapi)
app.start()
chat_id = "amirwolfgp"
app1 = PyTgCalls(app)
app1.start()
app1.play(
    chat_id,
    MediaStream(
        'http://docs.evostream.com/sample_content/assets/sintel1m720p.mp4',
        video_flags=MediaStream.Flags.IGNORE,
    )
)
app.run_until_disconnected()
```
ERROR:
```
PyTgCalls v2.0.6 powered by NTgCalls v1.2.3, Copyright (C) 2021-2024 Laky-64 <https://github.com/Laky-64>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Traceback (most recent call last):
  File "/home/a1069981/self.py", line 31, in <module>
    app1.play(
    ~~~~~~~~~^
        chat_id,
        ^^^^^^^^
    ...<2 lines>...
        )
        ^
    )
    ^
  File "/home/a1069981/.local/lib/python3.13/site-packages/pytgcalls/sync.py", line 55, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/rh/rh-python313/root/usr/lib64/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/a1069981/.local/lib/python3.13/site-packages/pytgcalls/mutex.py", line 9, in async_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a1069981/.local/lib/python3.13/site-packages/pytgcalls/statictypes.py", line 96, in async_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a1069981/.local/lib/python3.13/site-packages/pytgcalls/mtproto_required.py", line 23, in async_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a1069981/.local/lib/python3.13/site-packages/pytgcalls/methods/stream/play.py", line 87, in play
    result_params = await self._app.join_group_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home/a1069981/.local/lib/python3.13/site-packages/pytgcalls/mtproto/mtproto_client.py", line 62, in join_group_call
    return await self._bind_client.join_group_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home/a1069981/.local/lib/python3.13/site-packages/pytgcalls/mtproto/telethon_client.py", line 363, in join_group_call
    result: Updates = await self._app(
                      ^^^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "/home/a1069981/.local/lib/python3.13/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a1069981/.local/lib/python3.13/site-packages/telethon/client/users.py", line 43, in _call
    await r.resolve(self, utils)
  File "/home/a1069981/.local/lib/python3.13/site-packages/telethon/tl/functions/phone.py", line 694, in resolve
    self.join_as = utils.get_input_peer(await client.get_input_entity(self.join_as))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a1069981/.local/lib/python3.13/site-packages/telethon/client/users.py", line 446, in get_input_entity
    peer = utils.get_peer(peer)
  File "/home/a1069981/.local/lib/python3.13/site-packages/telethon/utils.py", line 987, in get_peer
    _raise_cast_fail(peer, 'Peer')
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/a1069981/.local/lib/python3.13/site-packages/telethon/utils.py", line 131, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
        type(entity).__name__, target))
TypeError: Cannot cast NoneType to any kind of Peer.```

**Comment by Laky-64** [comment]
Probably wrong chat username

**Comment by amirwolf5122** [comment]
> Probably wrong chat username

The group ID is correct. When entering the live stream and trying to play the video, it gives an error.
![Screenshot_2025-01-02-03-34-14-760_org telegram messenger web](https://github.com/user-attachments/assets/569ca23b-4678-4603-b563-594999c76eab)

**Comment by Laky-64** [comment]
Are you using any Pyrogram Fork?

**Comment by mhdeiiking** [comment]
@Laky-64 No

**Comment by amirwolf5122** [comment]
I am using **Telethon**, not the **Pyrogram fork**, and I have identified the issue: it wasn't working due to low CPU and RAM resources.
