### ISSUE TITLE
JS Syntax error while calling run(app)

### ISSUE THREAD

**Issue by ChaitanyaPy** [pytgcalls/pytgcalls#5]
My code:
```python
import pytgcalls
from pyrogram import Client
app = Client('session')

tg = pytgcalls.PyTgCalls(port=6540, log_mode=True)
tg.run(app)
tg.join_group_call(chat_id,  'input.raw', 160)
```

And this is the error I am getting while running `tg.run(app)`:
```
/home/chaitanya/my-python-stuff/pytgcalls_tests/pytgcalls/pytgcalls/js/rtc_connection.js:6
    #tgcalls = null;
    ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/chaitanya/my-python-stuff/pytgcalls_tests/pytgcalls/pytgcalls/js/core.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```
I don't understand what the problem is, have I set up something wrong?

**Comment by Laky-64** [comment]
Try to update your mode version

**Comment by ChaitanyaPy** [comment]
I have just updated to node version to `v15.10.0`. 
![image](https://user-images.githubusercontent.com/59993175/109099837-c668b180-7749-11eb-83e1-4096772b08fe.png)
But the issue still persists

**Comment by Laky-64** [comment]
Install the latest version of node

**Comment by Laky-64** [comment]
But you trying to join before the core has started....

**Comment by ChaitanyaPy** [comment]
Sorry I am a noob, but how do I let the core start?

**Comment by Laky-64** [comment]
Use a listener like pyrogram message listener

**Comment by ChaitanyaPy** [comment]
okay I have re-installed node, and I think that has fixed it...
Umm... where are the docs, can you please send the link for it?
Thanks for the help

**Comment by AndrewLaneX** [comment]
https://pytgcalls.github.io/

**Comment by ChaitanyaPy** [comment]
Is there a working example using this module in Python? I am not able to get the custom API and `join_group_call` functions working. please...

**Comment by KryDevs** [comment]
> Sorry I am a noob, but how do I let the core start?

**Comment by ChaitanyaPy** [comment]
Yea, I have updated node, and that issue doesn't persist now but, can I get some examples with the usage of this bot, please?
